
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('6 conditions','460');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Normal radiation on the abdomen','90');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Intestinal obstruction','130');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('The extravagant rays','110');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Barium - 6 conditions','700');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('The stomach and the twelve barium 6 films','700');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Small intestine (5 movies)','700');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Colon Barium','700');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Liver catheterization is done with','1600');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Bile ducts by tube','600');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Larynx status','90');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`)VALUES('Throat two positions','110');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Radiation on the chest','90');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Any extra chest condition','60');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Radiology of heart and chest Barium','160');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Duplex on veins (one hand)','300');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Duplex on the arteries (one hand)','240');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Neck veins','320');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Heart drawing','70');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Heart-drawing effort','240');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Draw a computer brain','360');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Draw a nerve or muscle','260');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Draw muscles and nerve one hand','340');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Draw two lateral muscles and nerve','240');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Drawing nerves and full muscles','600');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Draw muscles and nerves of anus','700');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Chest chest radiographs put one','90');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('One-party rays (2 modes)','100');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Detailed rays (two modes)','120');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Drosophila pelvis (two modes)','120');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Arthroscopy of the knee joint (two positions)','100');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Arthroscopy of the shoulder - forearm (two positions)','100');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Arthroscopy - Ankle (two positions)','100');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Elbow- Ankle-hand-foot- (2Viiews)','100');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Skull put one','90');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Skull and dice','110');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('The whole sinus group','170');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Cervical vertebrae','110');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Thoracic vertebrae','130');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Lumbar vertebrae','130');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Normal radiation','90');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('5 - color film','240');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Bladder and urethral canal with shingles','550');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Rising rays on the kidneys by dyeing through the catheter','550');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Installation of Nephrostomy','1400');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('The breast is one side CT scan on audio waves','400');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('The breasts are two sides of a cross-sectional sound waves','550');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('One breast (Digital)','550');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Two sides (Digital)','900');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Radiation on the uterus','600');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Single-hand spermatozoa','600');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('CT scan on the brain without dye','320');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('A CT scan of the brain','480');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Tumor of the pituitary gland - eye - ear - neck - throat and throat - pharynx (without dye)','440');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Tumor of the pituitary gland - eye, ear, neck, throat, pharynx,','680');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('A CT scan on the sinuses is one','320');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('CT scan on the sinuses is two modes','480');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('CT on the cervical vertebrae - chest - lumbar','500');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Chest CT on the chest - abdomen - pelvis without dye','500');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Chest CT on the chest - abdomen - pelvic dye','800');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('CT scan on the abdomen and pelvis together without dye','800');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('CT on the abdomen and pelvis dye hinge','1000');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Cross-sectional tomography and liver with three-phase pigment','1400');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('CT scan on one joint on one knee - shoulder - limb - take','500');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('A sample of pectorial scans','1400');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('A sample of pectorial scans on bone - lung - chest','1800');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('CT scan of the urinary tract without dye','700');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('CT scan of the urinary tract','880');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Digestive segmentation of the digestive tract (colon)','880');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('CT scan of the brain, kidney, neck, and lung arteries','1300');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Aortic scan on the aorta (chest-abdomen) in the dye','1300');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Cross - sectional radiographs - one side vein','1300');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Top and bottom lumbar cornea together','1500');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Computed tomography of the hepatic papillary vein','880');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Measuring the percentage of calcification in the arteries of the heart','500');
INSERT INTO `hcm`.`ray` (`Ray Name`, `Price`) VALUES('Examination of coronary arteries and heart and measuring calcification rate','3000');
